services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      - ConnectionStrings__DataAccess=Server=sqlserver;Database=teste_hiper;User Id=sa;Password=Pass@word;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
      - rabbitmq
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Porta do Protocolo AMQP
      - "15672:15672" # Porta da Interface Web
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
